# Generated by Django 5.1.6 on 2025-07-29 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZipArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('zip_file', models.FileField(upload_to='zips/')),
            ],
        ),
        migrations.DeleteModel(
            name='DownloadableFile',
        ),
        migrations.RemoveField(
            model_name='product',
            name='file',
        ),
    ]
