# Generated by Django 5.1.6 on 2025-07-29 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_ziparchive_delete_downloadablefile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='zip_file',
            field=models.FileField(blank=True, null=True, upload_to='zips/', verbose_name='ZIP архив'),
        ),
    ]
